### ISSUE TITLE
play videos from remote

### ISSUE THREAD

**Issue by sebastienboulogne** [antonyraphel/ARStories#1]
Hi, your code looks good but have some timing problems while playing videos from remote url :/ 

- Would you have a different version taking care of loading the videos before starting progress bar timing ?

- The first progress bar segment takes the default duration (5 sec) instead of the asset (video) duration ? How to fix that ?

Thank you so much for your help :)

**Comment by antonyraphel** [comment]
- [x] loading the videos before starting progress bar timing is done.
- [x] first progress bar segment takes the default duration (5 sec) instead of the asset (video) duration is done. 

@sebastienboulogne thanks for your update.
