### ISSUE TITLE
first story is not moving automatically after tapping only it is moving to next story.

### ISSUE THREAD

**Issue by praveen4D2** [antonyraphel/ARStories#2]

**Comment by kajalnasit** [comment]
just replace code 
DispatchQueue.main.async {
            self.SPB.currentAnimationIndex = 0
            self.SPB.startAnimation()
            self.playVideoOrLoadImage(index: 0)
        }
with 
DispatchQueue.main.asyncAfter(deadline: .now() + 0.2) {
            self.SPB.currentAnimationIndex = 0
            self.SPB.startAnimation()
            self.playVideoOrLoadImage(index: 0)
        }
working for me.

**Comment by antonyraphel** [comment]
It's updated now, @KajalNasit thanks for the fix.
